# Configuracion base de datos
spring.datasource.url=jdbc:h2:mem:seif;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.h2.tcp.enabled=true
spring.h2.tcp.port=9092
spring.h2.tcp.settings=-tcpAllowOthers
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true
# JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
#
spring.ldap.embedded.ldif=classpath:users.ldif
spring.ldap.embedded.base-dn=dc=bim,dc=org
spring.ldap.embedded.port=389
#ftp
ftp.host=drive.bim.mx
ftp.port=22
ftp.user=VMalvaez
ftp.password=6%f1exo-k0Ef
ftp.path=/BranchBit/filezillaFilesServer
ruta.guardar.instruccion=instrucciones
ruta.guardar.adicional=adicionales
ruta.guardar.estadosCuenta=estadosDeCuenta
#archivos
# Para MVC
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB


gestor.api.url=http://localhost:9002/fideicomisos


mail.from=Branchbit.1@bim.mx
mail.to=gvazquezh@mcllent.com