spring.application.name=seifclient
server.servlet.context-path=/seifclient
spring.mvc.pathmatch.matching-strategy=ant_path_matcher
server.error.whitelabel.enabled=false
#server.port=4200
springdoc.api-docs.path=/docs
spring.profiles.active=qa
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=INFO

#Expiration
auth.code.expiration=1115
auth.block.expiration=240
auth.block.attemps=3
# 24 horas en milisegundos (86400000 = 24 * 60 * 60 * 1000)
expiration.jwt.minutes=1000000

# Duración access token (5 a 15 min). Aquí 10 min:
security.oauth2.access-token.ttl-minutes=20

# Duración refresh token:
security.oauth2.refresh-token.ttl-days=30

# Logout: TTL de la lista de revocación (igual a exp del token)
security.oauth2.blacklist.prefix=bl:jwt:
security.oauth2.refresh.prefix=rt:
security.oauth2.jwk.kid=seif-kid-1
JWT_SECRET_BASE64=QE5jUmZValhuMnI1dTh4L0E/RChHK0tiUGRTZ1ZrWXA=
#archivos
server.tomcat.uri-encoding=UTF-8
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
spring.mvc.locale=es_MX
spring.web.locale=es_MX
