# Configuracion base de datos
spring.datasource.url=jdbc:sqlserver://172.30.28.53;databaseName=dbSEIF;port=1434;instanceName=desarrollo;encrypt=true;trustServerCertificate=true;networkProtocol=NamedPipes
#spring.datasource.url=jdbc:sqlserver://172.30.28.53;databaseName=dbSeifDesarrollo;port=1434;instanceName=desarrollo;encrypt=true;trustServerCertificate=true;networkProtocol=NamedPipes
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=Erick.Castillo
spring.datasource.password=Branchbit2025

spring.ldap.url=ldap://172.30.28.63:10389
#spring.ldap.url=ldap://localhost:10389
spring.ldap.base=dc=bim,dc=com


#ftp
ftp.host=drive.bim.mx
ftp.port=22
ftp.user=VMalvaez
ftp.password=6%f1exo-k0Ef
ftp.path=/BranchBit/filezillaFilesServer
ruta.guardar.instruccion=instrucciones
ruta.guardar.adicional=adicionales
ruta.guardar.estadosCuenta=estadosDeCuenta
#archivos
# Para MVC
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

gestor.api.url=http://172.30.28.63:7001/seif-manager/fideicomisos
#gestor.api.url=http://localhost:7001/seif-manager/fideicomisos


mail.from=Branchbit.1@bim.mx
mail.to=gvazquezh@mcllent.com
#fpedraza@mcllent.com