spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

gestor.api.url=http://localhost:7001/seif-manager/fideicomisos

spring.datasource.jndi-name=jdbc/seifDS
#ftp
ftp.host=drive.bim.mx
ftp.port=22
ftp.user=VMalvaez
ftp.password=6%f1exo-k0Ef
ftp.path=/BranchBit/filezillaFilesServer
ruta.guardar.instruccion=instrucciones
ruta.guardar.adicional=adicionales
ruta.guardar.estadosCuenta=estadosDeCuenta

mail.from=Branchbit.1@bim.mx
